version: 0.2
 
phases:

  install:

    commands:

      - wget -q https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip

      - unzip -q terraform_1.7.0_linux_amd64.zip

      - mv terraform /usr/local/bin/

      - terraform --version
 
  build:

    commands:

      - cd sftp-terraform

      - terraform init
 
artifacts:

  files:

    - '**/*'
 
